# Git
.git
.gitignore

# Docker
Dockerfile
.dockerignore

# IDE specific files
.idea
.vscode
*.swp
*.swo

# Build artifacts
bin/
dist/

# Temporary files
*.tmp
*.temp
*~

# OS specific
.DS_Store
Thumbs.db
